name: tests

on:
  pull_request:
    branches: [main, dev, staging, release/*]
    types:
      - opened # when a PR is opened
      - synchronize # when a PR is pushed to
      - reopened # when a PR is reopened
      - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    CARGO_TERM_COLOR: always
    NODE_OPTIONS: "--max-old-space-size=4096"
    NODE_ENV: "test"

defaults:
    run:
        shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

      - run: pnpm run build
